import { PERMISSIONS } from "./permissions";

export const PROFILE_PERMISSIONS = {
  ADMIN: Object.values(PERMISSIONS),

  COORDENADOR: [
    PERMISSIONS.PRODUTO_FINAL_VER,
    PERMISSIONS.FICHA_TECNICA_VER,

    PERMISSIONS.INSUMO_VER,
    PERMISSIONS.COMPRA_VER,
    PERMISSIONS.FORNECEDOR_VER,
    PERMISSIONS.AUDITORIA_ESTOQUE_VER,

    PERMISSIONS.RELATORIO_FINANCEIRO_VER,
    PERMISSIONS.CURVA_ABC_VER,
    PERMISSIONS.EXPORTACAO_DADOS_VER,

    PERMISSIONS.USUARIO_VER,
    PERMISSIONS.USUARIO_CRIAR,
    PERMISSIONS.USUARIO_EDITAR,

    PERMISSIONS.PRODUTO_VER,
    PERMISSIONS.PRODUTO_CRIAR,
    PERMISSIONS.PRODUTO_EDITAR,

    PERMISSIONS.ESTOQUE_VER,
    PERMISSIONS.ESTOQUE_ENTRADA,
    PERMISSIONS.ESTOQUE_SAIDA,
    PERMISSIONS.ESTOQUE_AJUSTE,

    PERMISSIONS.COMPRA_VER,
    PERMISSIONS.COMPRA_CRIAR,
    PERMISSIONS.COMPRA_EDITAR,

    PERMISSIONS.FINANCEIRO_VER,

    PERMISSIONS.LOJA_VER,
    PERMISSIONS.PERFIL_VER,
  ],

  GESTOR_AB: [
    PERMISSIONS.USUARIO_VER,

    PERMISSIONS.PRODUTO_VER,
    PERMISSIONS.PRODUTO_CRIAR,
    PERMISSIONS.PRODUTO_EDITAR,

    PERMISSIONS.ESTOQUE_VER,
    PERMISSIONS.ESTOQUE_ENTRADA,
    PERMISSIONS.ESTOQUE_SAIDA,
    PERMISSIONS.ESTOQUE_AJUSTE,

    PERMISSIONS.COMPRA_VER,
    PERMISSIONS.COMPRA_CRIAR,
  ],

  GERENTE: [
    PERMISSIONS.USUARIO_VER,
    PERMISSIONS.USUARIO_CRIAR,

    PERMISSIONS.PRODUTO_VER,

    PERMISSIONS.ESTOQUE_VER,
    PERMISSIONS.ESTOQUE_ENTRADA,
    PERMISSIONS.ESTOQUE_SAIDA,

    PERMISSIONS.COMPRA_VER,
  ],

  CHEFE_BAR: [
    PERMISSIONS.PRODUTO_VER,
    PERMISSIONS.ESTOQUE_VER,
    PERMISSIONS.ESTOQUE_ENTRADA,
    PERMISSIONS.ESTOQUE_SAIDA,
  ],

  CHEFE_COZINHA: [
    PERMISSIONS.PRODUTO_VER,
    PERMISSIONS.ESTOQUE_VER,
    PERMISSIONS.ESTOQUE_ENTRADA,
    PERMISSIONS.ESTOQUE_SAIDA,
  ],

  ESTOQUISTA: [
    PERMISSIONS.USUARIO_VER,
    PERMISSIONS.PRODUTO_VER,
    PERMISSIONS.ESTOQUE_VER,
    PERMISSIONS.ESTOQUE_ENTRADA,
    PERMISSIONS.ESTOQUE_SAIDA,
  ],

  COMPRAS: [
    PERMISSIONS.PRODUTO_VER,
    PERMISSIONS.COMPRA_VER,
    PERMISSIONS.COMPRA_CRIAR,
    PERMISSIONS.COMPRA_EDITAR,
  ],

  FINANCEIRO: [PERMISSIONS.FINANCEIRO_VER, PERMISSIONS.FINANCEIRO_EDITAR],
};
