import styled, { css } from "styled-components";
const sizes={sm:css`height:34px;padding:0 10px;font-size:${({theme})=>theme.font.size.sm};`,md:css`height:42px;padding:0 12px;font-size:${({theme})=>theme.font.size.md};`,lg:css`height:50px;padding:0 14px;font-size:${({theme})=>theme.font.size.lg};`};
export const Container=styled.div`width:${({$fullWidth})=>$fullWidth?"100%":"auto"};display:flex;flex-direction:column;gap:6px;`;
export const Label=styled.label`font-size:${({theme})=>theme.font.size.sm};font-weight:700;color:${({theme})=>theme.colors.text};`;
export const InputWrapper=styled.div`width:100%;display:flex;align-items:center;gap:8px;border-radius:${({theme})=>theme.radius.sm};border:1px solid ${({theme,$hasError})=>$hasError?theme.colors.error:theme.colors.border};background:${({theme})=>theme.colors.input};color:${({theme})=>theme.colors.text};transition:border-color .2s ease,box-shadow .2s ease,opacity .2s ease;${({$size})=>sizes[$size]||sizes.md} &:focus-within{border-color:${({theme,$hasError})=>$hasError?theme.colors.error:theme.colors.primary};box-shadow:0 0 0 3px ${({theme,$hasError})=>$hasError?`${theme.colors.error}22`:`${theme.colors.primary}22`};}${({$disabled})=>$disabled&&css`opacity:.55;cursor:not-allowed;`} ${({theme})=>theme.media.mobile}{height:40px;font-size:${({theme})=>theme.font.size.sm};}`;
export const StyledInput=styled.input`width:100%;height:100%;border:none;outline:none;background:transparent;color:${({theme})=>theme.colors.text};&::placeholder{color:${({theme})=>theme.colors.textMuted};}&:disabled{cursor:not-allowed;} &[type="number"]{appearance:textfield;} &[type="number"]::-webkit-inner-spin-button,&[type="number"]::-webkit-outer-spin-button{appearance:none;margin:0;}`;
export const IconBox=styled.span`display:inline-flex;align-items:center;justify-content:center;color:${({theme})=>theme.colors.textMuted};flex-shrink:0;`;
export const ErrorText=styled.span`font-size:${({theme})=>theme.font.size.xs};color:${({theme})=>theme.colors.error};`;
export const HelperText=styled.span`font-size:${({theme})=>theme.font.size.xs};color:${({theme})=>theme.colors.textMuted};`;
